# prefixキーをC-qに変更
unbind C-b
set -g prefix C-g

# PaneをVim-likeに移動する
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# ステータスバーの色を設定する
set -g status-bg "colour60"
set -g status-fg "colour236"

# window-status のフォーマットを指定する
setw -g window-status-format "#I:#W "
# カレントウィンドウの window-status のフォーマットを指定する
setw -g window-status-current-format "#[fg=colour254,bg=colour67] #I:#W"

# ステータスバーの右側の表示内容を空に設定
set -g status-right ""

#マウス操作を有効にする
set -g mouse on
#コピーモード時のキーバインドをVimに
setw -g mode-keys vi

# ヴィジュアルノーティフィケーションを無効にする
setw -g monitor-activity off
set -g visual-activity off

# ステータスバーを上部に表示する
set -g status-position top
# checkhealth回避用
set -g escape-time 10
set -g focus-events on

# tmuxのコピーモードからクリップボードにコピー
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -bi"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -bi"
