# Prefix
unbind C-b
set -g prefix C-q

# General
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g history-limit 50000
set -g focus-events on
set -g set-clipboard on

# Terminal & Color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Status bar
set -g status-position top
set -g status-right ""
set -g status-bg "colour60"
set -g status-fg "colour236"
setw -g window-status-format "#I:#W "
setw -g window-status-current-format "#[fg=colour254,bg=colour67] #I:#W"

# Pane navigation
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Splits inherit the current pane's working directory.
bind r split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
